export { default as HTML } from "./html.svg";
export { default as CSS } from "./css.svg";
export { default as JavaScript } from "./javascript.svg";
export { default as TypeScript } from "./typescript.svg";
export { default as TailwindCSS } from "./tailwindcss.svg";
export { default as React } from "./react.svg";
export { default as Nextjs } from "./nextjs.svg";
export { default as Vite } from "./vite.svg";
export { default as Remix } from "./remix.svg";
